services:
    postgres:
        image: postgres:17
        container_name: postgres_container
        environment:
            POSTGRES_DB: super_store_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - super_store_data:/var/lib/postgresql/data

    # ETL Service (Python container)
    etl:
        build:
            context: ./app

        container_name: etl_container
        depends_on:
            - postgres

        volumes:
            - ./app:/app
            - ./data:/app/data
            - ./logs:/app/logs
            - ./sql:/app/sql
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_DB: super_store_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin

volumes:
    super_store_data:
